version: "3"

services:
  redis:
    image: redis

  db:
    image: postgres:9.4
    environment:
      POSTGRES_PASSWORD: "postgres"
  vote:
    image: voting-app
    ports:
      - "5000:80"
    # If we are using version 3 we no longer need to link the containers
    # links:
    #   - redis

  worker:
    image: worker-app
    # links:
    #   - redis
    #   - db

  result:
    image: result-app
    ports:
      - "5001:80"
    # links:
    #   - db
